from selenium.webdriver.common.by import By

class TestLocators:
    search_personal_account = By.LINK_TEXT, "Личный Кабинет"
    search_registration = By.LINK_TEXT, "Зарегистрироваться"
    input_name = By.XPATH, "//label[text()='Имя']/following-sibling::input[@name='name']"
    input_email = By.XPATH, "//label[text()='Email']/following-sibling::input[@name='name']"
    input_password = By.NAME,"Пароль"
    button_registration = By.XPATH, ".//button[text()='Зарегистрироваться']"
    mistake_incorrect_password = By.XPATH, "//p[contains(text(), 'Некорректный пароль')]"
    search_input_element_text = By.XPATH, ".//h2"
    button_input = By.XPATH, ".//button[text()='Войти']"
    search_sign_in_main = By.XPATH, ".//button[text()='Войти в аккаунт']"
    search_sign_in_throw_registration_and_recovery = By.XPATH, "//a[@class='Auth_link__1fOlj' and @href='/login']"
    search_forgot_password = By.XPATH, "//a[@class='Auth_link__1fOlj' and @href='/forgot-password']"
    search_exit_acc = By.XPATH, ".//button[text()='Выход']"
    button_constructor = By.XPATH, ".//p[text()='Конструктор']"
    logo_stellar_burgers = By.CSS_SELECTOR, ".AppHeader_header__logo__2D0X2"
    button_main_breads = By.XPATH, "//span[text()='Булки']"
    button_main_sauces = By.XPATH, "//span[text()='Соусы']"
    button_main_fillings = By.XPATH, "//span[text()='Начинки']"
    button_order = By.XPATH, "//button[contains(text(), 'Оформить заказ')]"
    search_breads = By.XPATH, "//p[text()='Флюоресцентная булка R2-D3']"
    search_sauces = By.XPATH, "//p[text()='Соус Spicy-X']"
    search_fillings = By.XPATH, "//p[text()='Биокотлета из марсианской Магнолии']"
    condition_sauces = By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG') and span[text()='Соусы']]"
    condition_breads = By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG') and span[text()='Булки']]"
    condition_fillings = By.XPATH, "//div[contains(@class, 'tab_tab__1SPyG') and span[text()='Начинки']]"